language: julia

os:
    - linux
    - osx

julia:
    - 1.0
    - 1.2
    - nightly

matrix:
    allow_failures:
        - julia: nightly

notifications:
    email: false

before_install:
    # If it is linux, we must install `libncurses`.
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --reinstall libncurses5     libncursesw5;     fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --reinstall libncurses5-dev libncursesw5-dev; fi

after_success:
    # Push coverage results to Coveralls.
    - julia -e 'import Pkg; cd(Pkg.dir("TextUserInterfaces")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
    # Push coverage results to Codecov.
    - julia -e 'import Pkg; cd(Pkg.dir("TextUserInterfaces")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip
